INSERT INTO destination_city (country_id, city_name) VALUES(1 ,'Анталия');
INSERT INTO destination_city (country_id, city_name) VALUES(1 ,'Бодрум');
INSERT INTO destination_city (country_id, city_name) VALUES(1 ,'Измир');
INSERT INTO destination_city (country_id, city_name) VALUES(1 ,'Даламан');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Салоники');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Араксос');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Ираклион');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Корфу');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Родос');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'о. Кос');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Закинф');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Санторини');
INSERT INTO destination_city (country_id, city_name) VALUES(2 ,'Александруполис');
INSERT INTO destination_city (country_id, city_name) VALUES(3 ,'Барселона');
INSERT INTO destination_city (country_id, city_name) VALUES(3 ,'Рейна София');
INSERT INTO destination_city (country_id, city_name) VALUES(3 ,'Пальма-де-Майорка');
INSERT INTO destination_city (country_id, city_name) VALUES(3 ,'Малага');
INSERT INTO destination_city (country_id, city_name) VALUES(3 ,'Аликанте');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Марко Поло');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Генуя');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Римини');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Рим');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Неаполь');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Катания');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Наполи');
INSERT INTO destination_city (country_id, city_name) VALUES(4 ,'Милан');
INSERT INTO destination_city (country_id, city_name) VALUES(5 ,'Ларнака');
INSERT INTO destination_city (country_id, city_name) VALUES(5 ,'Пафос');
INSERT INTO destination_city (country_id, city_name) VALUES(6 ,'Варна');
INSERT INTO destination_city (country_id, city_name) VALUES(7 ,'Хо Ши Мин');
INSERT INTO destination_city (country_id, city_name) VALUES(8 ,'Бангкок');
INSERT INTO destination_city (country_id, city_name) VALUES(8 ,'Пхукет');
INSERT INTO destination_city (country_id, city_name) VALUES(9 ,'Самана');
INSERT INTO destination_city (country_id, city_name) VALUES(10 ,'Даболин');
INSERT INTO destination_city (country_id, city_name) VALUES(11 ,'Дубаи');
INSERT INTO destination_city (country_id, city_name) VALUES(12 ,'Монастир');
INSERT INTO destination_city (country_id, city_name) VALUES(13 ,'Бандаранайке');
INSERT INTO destination_city (country_id, city_name) VALUES(14 ,'Ngurah Rai');
INSERT INTO destination_city (country_id, city_name) VALUES(15 ,'Кункун');
INSERT INTO destination_city (country_id, city_name) VALUES(16 ,'Хулуле');
INSERT INTO destination_city (country_id, city_name) VALUES(17 ,'Варадеро');
INSERT INTO destination_city (country_id, city_name) VALUES(18 ,'Тиват');
INSERT INTO destination_city (country_id, city_name) VALUES(19 ,'Сплит');
INSERT INTO destination_city (country_id, city_name) VALUES(20 ,'Кота Кинабалу');
INSERT INTO destination_city (country_id, city_name) VALUES(21 ,'Тагбиларан');
INSERT INTO destination_city (country_id, city_name) VALUES(22 ,'Плезанс');
INSERT INTO destination_city (country_id, city_name) VALUES(23 ,'Мэйлэн');
INSERT INTO destination_city (country_id, city_name) VALUES(24 ,'Шарль де Голь');
INSERT INTO destination_city (country_id, city_name) VALUES(25 ,'Мадейра');
INSERT INTO destination_city (country_id, city_name) VALUES(26 ,'Прага');
INSERT INTO destination_city (country_id, city_name) VALUES(27 ,'Шарм-эль-Шейх');
INSERT INTO destination_city (country_id, city_name) VALUES(27 ,'Таба');