INSERT INTO countries(country_name) VALUES('Турция');
INSERT INTO countries(country_name) VALUES('Греция');
INSERT INTO countries(country_name) VALUES('Испания');
INSERT INTO countries(country_name) VALUES('Италия');
INSERT INTO countries(country_name) VALUES('Кипр');
INSERT INTO countries(country_name) VALUES('Болгария');
INSERT INTO countries(country_name) VALUES('Вьетнам');
INSERT INTO countries(country_name) VALUES('Тайланд');
INSERT INTO countries(country_name) VALUES('Доминикана');
INSERT INTO countries(country_name) VALUES('Индия');
INSERT INTO countries(country_name) VALUES('ОАЭ');
INSERT INTO countries(country_name) VALUES('Тунис');
INSERT INTO countries(country_name) VALUES('Шри Ланка');
INSERT INTO countries(country_name) VALUES('Бали');
INSERT INTO countries(country_name) VALUES('Мексика');
INSERT INTO countries(country_name) VALUES('Мальдивы');
INSERT INTO countries(country_name) VALUES('Куба');
INSERT INTO countries(country_name) VALUES('Черногория');
INSERT INTO countries(country_name) VALUES('Хорватия');
INSERT INTO countries(country_name) VALUES('Малайзия');
INSERT INTO countries(country_name) VALUES('Филиппины');
INSERT INTO countries(country_name) VALUES('Маврикий');
INSERT INTO countries(country_name) VALUES('Китай');
INSERT INTO countries(country_name) VALUES('Франция');
INSERT INTO countries(country_name) VALUES('Португалия');
INSERT INTO countries(country_name) VALUES('Чехия');
INSERT INTO countries(country_name) VALUES('Египет');
INSERT INTO countries(country_name) VALUES('Российская Федерация');
INSERT INTO countries(country_name) VALUES('Республика Беларусь');
INSERT INTO countries(country_name) VALUES('Украина');