INSERT INTO places (country_id, place_name) VALUES(1, 'Анталия');
INSERT INTO places (country_id, place_name) VALUES(1, 'Алания');
INSERT INTO places (country_id, place_name) VALUES(1, 'Белек');
INSERT INTO places (country_id, place_name) VALUES(1, 'Кемер');
INSERT INTO places (country_id, place_name) VALUES(1, 'Сиде');
INSERT INTO places (country_id, place_name) VALUES(1, 'Бодрум');
INSERT INTO places (country_id, place_name) VALUES(1, 'Кушадасы');
INSERT INTO places (country_id, place_name) VALUES(1, 'Мармарис');
INSERT INTO places (country_id, place_name) VALUES(1, 'Фетхие');
INSERT INTO places (country_id, place_name) VALUES(2, 'Халкидики');
INSERT INTO places (country_id, place_name) VALUES(2, 'Пелопоннес');
INSERT INTO places (country_id, place_name) VALUES(2, 'Крит');
INSERT INTO places (country_id, place_name) VALUES(2, 'Корфу');
INSERT INTO places (country_id, place_name) VALUES(2, 'Родос');
INSERT INTO places (country_id, place_name) VALUES(2, 'Кос');
INSERT INTO places (country_id, place_name) VALUES(2, 'Закинф');
INSERT INTO places (country_id, place_name) VALUES(2, 'Санторини');
INSERT INTO places (country_id, place_name) VALUES(2, 'Александруполис');
INSERT INTO places (country_id, place_name) VALUES(3, 'Коста Дорада');
INSERT INTO places (country_id, place_name) VALUES(3, 'Коста Брава');
INSERT INTO places (country_id, place_name) VALUES(3, 'Тенерифе');
INSERT INTO places (country_id, place_name) VALUES(3, 'Майорка');
INSERT INTO places (country_id, place_name) VALUES(3, 'Коста Дель Соль');
INSERT INTO places (country_id, place_name) VALUES(3, 'Коста Бланка');
INSERT INTO places (country_id, place_name) VALUES(3, 'Коста Калида');
INSERT INTO places (country_id, place_name) VALUES(4, 'Венецианская ривьера');
INSERT INTO places (country_id, place_name) VALUES(4, 'Лигурийское побережье');
INSERT INTO places (country_id, place_name) VALUES(4, 'Адриатическое побережье');
INSERT INTO places (country_id, place_name) VALUES(4, 'Ривьера-Ди-Улиссе');
INSERT INTO places (country_id, place_name) VALUES(4, 'Неаполитанская ривьера');
INSERT INTO places (country_id, place_name) VALUES(4, 'о. Искья');
INSERT INTO places (country_id, place_name) VALUES(4, 'о. Капри');
INSERT INTO places (country_id, place_name) VALUES(4, 'Сицилия');
INSERT INTO places (country_id, place_name) VALUES(4, 'Побережье Челенто');
INSERT INTO places (country_id, place_name) VALUES(4, 'Озеро Лаго-Маджоре');
INSERT INTO places (country_id, place_name) VALUES(4, 'Тоскана');
INSERT INTO places (country_id, place_name) VALUES(5, 'Лимассол');
INSERT INTO places (country_id, place_name) VALUES(5, 'Айа Напа');
INSERT INTO places (country_id, place_name) VALUES(5, 'Ларнака');
INSERT INTO places (country_id, place_name) VALUES(5, 'Пафос');
INSERT INTO places (country_id, place_name) VALUES(5, 'Протарас');
INSERT INTO places (country_id, place_name) VALUES(6, 'Дюни');
INSERT INTO places (country_id, place_name) VALUES(6, 'Русалка');
INSERT INTO places (country_id, place_name) VALUES(6, 'Елените');
INSERT INTO places (country_id, place_name) VALUES(6, 'Солнечный Берег');
INSERT INTO places (country_id, place_name) VALUES(6, 'Ривьера');
INSERT INTO places (country_id, place_name) VALUES(6, 'Поморье');
INSERT INTO places (country_id, place_name) VALUES(6, 'Албена');
INSERT INTO places (country_id, place_name) VALUES(6, 'Солнечный День');
INSERT INTO places (country_id, place_name) VALUES(6, 'Св. Константин и Елена');
INSERT INTO places (country_id, place_name) VALUES(6, 'Несебр');
INSERT INTO places (country_id, place_name) VALUES(6, 'Золотые пески');
INSERT INTO places (country_id, place_name) VALUES(6, 'Созополь');
INSERT INTO places (country_id, place_name) VALUES(7, 'Фантьет - Муйне');
INSERT INTO places (country_id, place_name) VALUES(7, 'Нья Чанг');
INSERT INTO places (country_id, place_name) VALUES(7, 'Остров Фу Куок');
INSERT INTO places (country_id, place_name) VALUES(8, 'Бангкок');
INSERT INTO places (country_id, place_name) VALUES(8, 'Паттайа');
INSERT INTO places (country_id, place_name) VALUES(8, 'Пхукет');
INSERT INTO places (country_id, place_name) VALUES(8, 'Самуи');
INSERT INTO places (country_id, place_name) VALUES(8, 'Чанг');
INSERT INTO places (country_id, place_name) VALUES(8, 'Пхи-Пхи');
INSERT INTO places (country_id, place_name) VALUES(8, 'Краби');
INSERT INTO places (country_id, place_name) VALUES(8, 'Као Лак');
INSERT INTO places (country_id, place_name) VALUES(9, 'Пунта Кана');
INSERT INTO places (country_id, place_name) VALUES(9, 'Пуэрто Плата');
INSERT INTO places (country_id, place_name) VALUES(9, 'Самана');
INSERT INTO places (country_id, place_name) VALUES(9, 'Ла Романа');
INSERT INTO places (country_id, place_name) VALUES(10, 'Северное Гоа');
INSERT INTO places (country_id, place_name) VALUES(10, 'Центральное Гоа');
INSERT INTO places (country_id, place_name) VALUES(10, 'Южное Гоа');
INSERT INTO places (country_id, place_name) VALUES(11, 'Дубаи');
INSERT INTO places (country_id, place_name) VALUES(11, 'Джумейра');
INSERT INTO places (country_id, place_name) VALUES(11, 'Шарджа');
INSERT INTO places (country_id, place_name) VALUES(11, 'Фуджейра');
INSERT INTO places (country_id, place_name) VALUES(11, 'Рас Аль Хайма');
INSERT INTO places (country_id, place_name) VALUES(11, 'Абу Даби');
INSERT INTO places (country_id, place_name) VALUES(11, 'Аджман');
INSERT INTO places (country_id, place_name) VALUES(12, 'Хаммамет');
INSERT INTO places (country_id, place_name) VALUES(12, 'Сусс');
INSERT INTO places (country_id, place_name) VALUES(12, 'Монастир');
INSERT INTO places (country_id, place_name) VALUES(12, 'Махдия');
INSERT INTO places (country_id, place_name) VALUES(12, 'Джерба');
INSERT INTO places (country_id, place_name) VALUES(13, 'Индурува');
INSERT INTO places (country_id, place_name) VALUES(13, 'Тангалле');
INSERT INTO places (country_id, place_name) VALUES(13, 'Маравила');
INSERT INTO places (country_id, place_name) VALUES(13, 'Ахунгала');
INSERT INTO places (country_id, place_name) VALUES(13, 'Коггала');
INSERT INTO places (country_id, place_name) VALUES(13, 'Диквелла');
INSERT INTO places (country_id, place_name) VALUES(13, 'Коломбо');
INSERT INTO places (country_id, place_name) VALUES(13, 'Галле');
INSERT INTO places (country_id, place_name) VALUES(13, 'Ваддува');
INSERT INTO places (country_id, place_name) VALUES(13, 'Калутара');
INSERT INTO places (country_id, place_name) VALUES(13, 'Бентота');
INSERT INTO places (country_id, place_name) VALUES(13, 'Берувелла');
INSERT INTO places (country_id, place_name) VALUES(13, 'Хиккадува');
INSERT INTO places (country_id, place_name) VALUES(13, 'Негомбо');
INSERT INTO places (country_id, place_name) VALUES(13, 'Косгода');
INSERT INTO places (country_id, place_name) VALUES(13, 'Маунт Лавиния');
INSERT INTO places (country_id, place_name) VALUES(13, 'Экскурсионные отели');
INSERT INTO places (country_id, place_name) VALUES(14, 'Нуса Дуа');
INSERT INTO places (country_id, place_name) VALUES(14, 'Танджунг Беноа');
INSERT INTO places (country_id, place_name) VALUES(14, 'Джимбаран');
INSERT INTO places (country_id, place_name) VALUES(14, 'Кута');
INSERT INTO places (country_id, place_name) VALUES(14, 'Санур');
INSERT INTO places (country_id, place_name) VALUES(14, 'Семиньяк');
INSERT INTO places (country_id, place_name) VALUES(15, 'Ривьера-Майя');
INSERT INTO places (country_id, place_name) VALUES(15, 'Канкун');
INSERT INTO places (country_id, place_name) VALUES(15, 'Акапулько');
INSERT INTO places (country_id, place_name) VALUES(16, 'г. Мале');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Мале - юг');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Мале - север');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Таа');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Фаафу');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Даалу');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Баа');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Мииму');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Ноону');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Хаа Алифу');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Лавиани');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Адду');
INSERT INTO places (country_id, place_name) VALUES(16, 'Атолл Ари');
INSERT INTO places (country_id, place_name) VALUES(17, 'Варадеро');
INSERT INTO places (country_id, place_name) VALUES(18, 'Бечичи');
INSERT INTO places (country_id, place_name) VALUES(18, 'Будва');
INSERT INTO places (country_id, place_name) VALUES(18, 'Петровац');
INSERT INTO places (country_id, place_name) VALUES(18, 'Пржно');
INSERT INTO places (country_id, place_name) VALUES(18, 'Святой Стефан');
INSERT INTO places (country_id, place_name) VALUES(18, 'Ульцинь');
INSERT INTO places (country_id, place_name) VALUES(19, 'Истрия');
INSERT INTO places (country_id, place_name) VALUES(19, 'Южная Далмация');
INSERT INTO places (country_id, place_name) VALUES(19, 'Средняя Далмация');
INSERT INTO places (country_id, place_name) VALUES(19, 'Северная Далмация');
INSERT INTO places (country_id, place_name) VALUES(20, 'Лангкави');
INSERT INTO places (country_id, place_name) VALUES(20, 'Борнео');
INSERT INTO places (country_id, place_name) VALUES(20, 'Пенанг');
INSERT INTO places (country_id, place_name) VALUES(20, 'Куала Лумпур');
INSERT INTO places (country_id, place_name) VALUES(21, 'Боракай');
INSERT INTO places (country_id, place_name) VALUES(21, 'Бохоль');
INSERT INTO places (country_id, place_name) VALUES(21, 'Палаван');
INSERT INTO places (country_id, place_name) VALUES(21, 'Себу');
INSERT INTO places (country_id, place_name) VALUES(21, 'Манила');
INSERT INTO places (country_id, place_name) VALUES(22, 'Западное побережье');
INSERT INTO places (country_id, place_name) VALUES(22, 'Южное побережье');
INSERT INTO places (country_id, place_name) VALUES(22, 'Восточное побережье');
INSERT INTO places (country_id, place_name) VALUES(22, 'Северное побережье');
INSERT INTO places (country_id, place_name) VALUES(23, 'Хайнань');
INSERT INTO places (country_id, place_name) VALUES(24, 'Париж');
INSERT INTO places (country_id, place_name) VALUES(25, 'Лиссабон');
INSERT INTO places (country_id, place_name) VALUES(25, 'Алгарве');
INSERT INTO places (country_id, place_name) VALUES(25, 'Лиссабонская Ривьера');
INSERT INTO places (country_id, place_name) VALUES(25, 'о. Мадейра');
INSERT INTO places (country_id, place_name) VALUES(26, 'Прага');
INSERT INTO places (country_id, place_name) VALUES(26, 'Карловы Вары');
INSERT INTO places (country_id, place_name) VALUES(26, 'Марианские Лазне');
INSERT INTO places (country_id, place_name) VALUES(26, 'Франтишковы Лазне');
INSERT INTO places (country_id, place_name) VALUES(27, 'Шарм Эль Шейх');
INSERT INTO places (country_id, place_name) VALUES(27, 'Хургада');
INSERT INTO places (country_id, place_name) VALUES(27, 'Макади');
INSERT INTO places (country_id, place_name) VALUES(27, 'Таба');
INSERT INTO places (country_id, place_name) VALUES(27, 'Нувейба');
INSERT INTO places (country_id, place_name) VALUES(27, 'Дахаб');
INSERT INTO places (country_id, place_name) VALUES(27, 'Эль Гуна');
INSERT INTO places (country_id, place_name) VALUES(27, 'Сома-бей');
INSERT INTO places (country_id, place_name) VALUES(27, 'Сафага');
INSERT INTO places (country_id, place_name) VALUES(27, 'Марса Алам');