INSERT INTO accomodation (accomodation_name, description) VALUES("DBL", 'двухместный номер c одной большой двуспальной кроватью');
INSERT INTO accomodation (accomodation_name, description) VALUES("TWIN", 'двухместный номер с двумя раздельными кроватями');
INSERT INTO accomodation (accomodation_name, description) VALUES("SGL", 'одноместный номер');
INSERT INTO accomodation (accomodation_name, description) VALUES("EXB (extra bed)", 'дополнительная кровать');
INSERT INTO accomodation (accomodation_name, description) VALUES("Tripl", 'трёхместный номер');
INSERT INTO accomodation (accomodation_name, description) VALUES("ch", 'маленький ребёнок, например, 2-6 лет (уточняйте у конкретного отеля)');
INSERT INTO accomodation (accomodation_name, description) VALUES("CH", 'большой ребёнок, как правило, до 12 лет, но в ряде отелей – до 15 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("Sc", 'маленький ребёнок + 1 взрослый');
INSERT INTO accomodation (accomodation_name, description) VALUES("SC", 'большой ребёнок + 1 взрослый');
INSERT INTO accomodation (accomodation_name, description) VALUES("Dc", 'маленький ребёнок + 2 взрослых');
INSERT INTO accomodation (accomodation_name, description) VALUES("DC", 'большой ребёнок + 2 взрослых');
INSERT INTO accomodation (accomodation_name, description) VALUES("DBL+ 2CHD (2-6)", '2 взрослых + 2 детей 2-6 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("2 ADL + 2 CHD (2-6) (2-12)", '2 взрослых + 2 детей от (первый ребёнок 2-6 лет, второй – 6-12 лет)');
INSERT INTO accomodation (accomodation_name, description) VALUES("2 ADL + 2 CHD (6-12)", '2 взрослых + 2 детей 6-12 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("Inf (infant)", 'ребёнок до 2 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("Qdpl", 'четырехместный номер');
INSERT INTO accomodation (accomodation_name, description) VALUES("Tripl +1 СHD (2-6)", 'трёхместный + ребёнок 2-6 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("3 ad + 1 CHD (2-12)", 'трёхместный + ребёнок 6-12 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("3ad + 2ch(2-6)", 'трёхместный + двое детей 2-6 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("3ad + 2ch (2-12) (2-6)", 'трёхместный + 2 детей: первый ребёнок 2-12 лет, второй – 2-6 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("3ad + 2ch (2-12)", 'трёхместный + двое детей 2-12 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("4ad + 1ch (2-5)", 'четырёхместный + 1 ребёнок 2-5 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("4ad + 1ch (6-12)", 'четырёхместный + 1 ребёнок 6-12 лет');
INSERT INTO accomodation (accomodation_name, description) VALUES("5ad", '	пятиместный');
INSERT INTO accomodation (accomodation_name, description) VALUES("BO (bed only)", 'размещение без питания');