INSERT INTO hotel_category (hotel_category_name, description) VALUES("1*", 'одна звезда');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("2*", 'две звезды');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("3*", 'три звезды');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("4*", 'четыре звезды');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("5*", 'пять звезд');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("Cat De Luxe", 'категория De Luxe');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("Cat A", 'четыре звезды');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("Cat B", 'три звезды');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("Cat C", 'две звезды');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("Cat D", 'одна звезда');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("HV", 'клубный отель');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("HV1", 'клубный отель 4-5 звезд (holiday village) – 1 (= 5*)');
INSERT INTO hotel_category (hotel_category_name, description) VALUES("HV2", 'клубный отель 3-4 звезды (= 3*, 3*+)');