INSERT INTO room_types (room_type_name, description) VALUES('1 BDRM', 'апартаменты с одной спальней');
INSERT INTO room_types (room_type_name, description) VALUES('2 BDRM', 'апартаменты с двумя спальнями');
INSERT INTO room_types (room_type_name, description) VALUES('Apartment', 'тип номеров в гостиницах, приближенных к виду современных квартир, имеющих места для приготовления еды (стоимость питания обычно не включается в стоимость номера); квартира из двух и более комнат с кухней');
INSERT INTO room_types (room_type_name, description) VALUES('Balcony Room', 'номер с балконом');
INSERT INTO room_types (room_type_name, description) VALUES('BG (bungalo)', 'бунгало – отдельная постройка, используемая для размещения туристов; часто предлагается в южных странах');
INSERT INTO room_types (room_type_name, description) VALUES('Cabana', 'род бунгало на пляже (или возле бассейна), стоящего отдельно от основного здания и иногда оборудованного как спальня');
INSERT INTO room_types (room_type_name, description) VALUES('De Luxe', 'номера повышенной комфортности');
INSERT INTO room_types (room_type_name, description) VALUES('Duplex', 'двухэтажный номер');
INSERT INTO room_types (room_type_name, description) VALUES('Executive floor', 'один или несколько этажей в отеле с более высоким уровнем обслуживания, а также дополнительным набором услуг');
INSERT INTO room_types (room_type_name, description) VALUES('Family Room', 'семейный номер размером больше стандартного (часто из двух комнат)');
INSERT INTO room_types (room_type_name, description) VALUES('Honeymoon Room', 'номер для молодожёнов');
INSERT INTO room_types (room_type_name, description) VALUES('HV (Holiday Village)', 'отель, представляющий собой комплекс бунгало');
INSERT INTO room_types (room_type_name, description) VALUES('Kingsize Bed', '«королевская кровать» (шириной более 180 см)');
INSERT INTO room_types (room_type_name, description) VALUES('King Suite', '«королевский сьют»');
INSERT INTO room_types (room_type_name, description) VALUES('MB (main building)', 'основное здание');
INSERT INTO room_types (room_type_name, description) VALUES('New Building', 'новый корпус');
INSERT INTO room_types (room_type_name, description) VALUES('Sitting area', 'зона для отдыха – часть номера, где располагаются кресла, журнальный столик, иногда также диван');
INSERT INTO room_types (room_type_name, description) VALUES('Standart', 'стандартная комната');
INSERT INTO room_types (room_type_name, description) VALUES('Studio', 'однокомнатный номер больше стандартного, с небольшой низкой перегородкой; или однокомнатная квартира с небольшой кухней, совмещённой с комнатой');
INSERT INTO room_types (room_type_name, description) VALUES('Suite', 'номер повышенной комфортности, как правило – одна комната большой площади, с зоной для отдыха');
INSERT INTO room_types (room_type_name, description) VALUES('Suite Executive', 'как правило, «сьют» с двумя спальнями');
INSERT INTO room_types (room_type_name, description) VALUES('Suite Junior', 'номер повышенной комфортности: обычно большая комфортабельная комната с отгороженным спальным местом, днём исполняющим роль гостиной');
INSERT INTO room_types (room_type_name, description) VALUES('Suite Mini', 'номер улучшенной категории');
INSERT INTO room_types (room_type_name, description) VALUES('номер улучшенной категории', '');
INSERT INTO room_types (room_type_name, description) VALUES('Suite Senior', 'номер повышенной комфортности, как правило, двухкомнатный: гостиная и спальня');
INSERT INTO room_types (room_type_name, description) VALUES('Superior', 'комната большего размера, чем стандартная');
INSERT INTO room_types (room_type_name, description) VALUES('Superior Chalet', 'шале повышенной комфортности');
INSERT INTO room_types (room_type_name, description) VALUES('Superior / Main Building', 'комната большего размера в главном здании');
INSERT INTO room_types (room_type_name, description) VALUES('Сonnected Rooms', 'совмещённые номера, имеющие дверь-проход из одного в другой');
INSERT INTO room_types (room_type_name, description) VALUES('Prisedent Suite', '«президентский сьют»');
INSERT INTO room_types (room_type_name, description) VALUES('Villas ', 'вид на море, парк');