INSERT INTO food (food_name, description) VALUES("Ep", 'без питания');
INSERT INTO food (food_name, description) VALUES("BB", 'затраки');
INSERT INTO food (food_name, description) VALUES("HB", 'полупансион');
INSERT INTO food (food_name, description) VALUES("HB+", 'расширенный полупансион');
INSERT INTO food (food_name, description) VALUES("FB", 'полный пансион');
INSERT INTO food (food_name, description) VALUES("FB+", 'расширенный полный пансион с напитками местного производства во время еды');
INSERT INTO food (food_name, description) VALUES("mini all inclusive", 'полный пансион с напитками местного производства не только во время еды, но в ограниченном количестве');
INSERT INTO food (food_name, description) VALUES("all inc", 'питание в течение дня, включая напитки местного производства в неограниченном количестве');
INSERT INTO food (food_name, description) VALUES("ultra all inc", 'питание в течение дня, включая напитки импортного производства (в том числе спиртные) плюс дополнительные услуги на усмотрение администрации отеля');
INSERT INTO food (food_name, description) VALUES("elegance all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("VIP all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("super all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("deluxe all Inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("VC all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("superior all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("mega all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("superior all inc VIP service", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("royal class all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("ultra deluxe all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("extended all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("excellent all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("max all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("high class all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("Imperial all inc", 'разновидность ultra all inc');
INSERT INTO food (food_name, description) VALUES("соntinental breakfast", 'континентальный завтрак: кофе или чай, сок, булочка, масло и джем');
INSERT INTO food (food_name, description) VALUES("english breakfast", 'полный завтрак, обычно включает в себя фруктовый сок, яичницу с ветчиной, тосты, масло, джем, кофе или чай');
INSERT INTO food (food_name, description) VALUES("american breakfast / buffet", 'род континентального завтрака, дополненный различными нарезками (колбаса, сыр) и горячими блюдами (омлет, сосиски)');
INSERT INTO food (food_name, description) VALUES("a-la carte", 'меню, в котором каждое блюдо указано со своей отдельной ценой');
INSERT INTO food (food_name, description) VALUES("питание по меню", 'ограниченное число блюд из меню, кроме морепродуктов');